// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/answer.tsx";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/api/random-uuid.ts";
import * as $7 from "./routes/cakes.tsx";
import * as $8 from "./routes/countdown.tsx";
import * as $9 from "./routes/delivery.tsx";
import * as $10 from "./routes/filling.tsx";
import * as $11 from "./routes/github/[username].tsx";
import * as $12 from "./routes/greet/[name].tsx";
import * as $13 from "./routes/index.tsx";
import * as $14 from "./routes/search.tsx";
import * as $$0 from "./islands/Card.tsx";
import * as $$1 from "./islands/Countdown.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/FakeStore.tsx";
import * as $$4 from "./islands/Hello.tsx";
import * as $$5 from "./islands/Hero.tsx";
import * as $$6 from "./islands/IndexContent.tsx";
import * as $$7 from "./islands/Openai.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/about.tsx": $3,
    "./routes/answer.tsx": $4,
    "./routes/api/joke.ts": $5,
    "./routes/api/random-uuid.ts": $6,
    "./routes/cakes.tsx": $7,
    "./routes/countdown.tsx": $8,
    "./routes/delivery.tsx": $9,
    "./routes/filling.tsx": $10,
    "./routes/github/[username].tsx": $11,
    "./routes/greet/[name].tsx": $12,
    "./routes/index.tsx": $13,
    "./routes/search.tsx": $14,
  },
  islands: {
    "./islands/Card.tsx": $$0,
    "./islands/Countdown.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/FakeStore.tsx": $$3,
    "./islands/Hello.tsx": $$4,
    "./islands/Hero.tsx": $$5,
    "./islands/IndexContent.tsx": $$6,
    "./islands/Openai.tsx": $$7,
  },
  baseUrl: import.meta.url,
};

export default manifest;
